spring.application.name=gattai
anilist.base-url=${ANILIST_BASE_URL:https://graphql.anilist.co}
kitsu.base-url=${KITSU_BASE_URL:https://kitsu.io/api/edge}
mal.base-url=${MAL_BASE_URL:https://api.myanimelist.net/v2/}
mal.client-id=${MAL_CLIENT_ID}
